name: Sync main to prod

on:
  push:
    branches:
      - main

jobs:
  sync-to-prod:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_PAT_2 }}

     
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

    
      - name: Fetch all branches
        run: git fetch origin

    
      - name: Checkout prod
        run: git checkout prod || git checkout -b prod

 
      - name: Merge main into prod
        run: |
          git merge origin/main --no-edit || echo "Merge conflicts, please resolve manually"

     
      - name: Push prod
        run: git push https://x-access-token:${{ secrets.PERSONAL_PAT_2 }}@github.com/hrovise/writer_front_Angular.git prod